### ISSUE TITLE
Pas de concentrateur Homekit ?

### ISSUE THREAD

**Issue by Clem-** [jeedom/plugin-homebridge#46]
J'ai remarqué que j'ai désormais un message d'erreur qui s'affiche sur la configuration du plugins au niveau de l'adresse IP Homebridge :
`Info : Vous n'avez pas de concentrateur Homekit, homebridge ne fonctionnera pas à distance`

J'ai effectivement constaté qu'en dehors de mon réseau local, je n'ai plus mes accessoires Homebridge de disponible.
J'ai bien deux concentrateurs Homekit (AppleTV+iPad) qui fonctionne bien à l'extérieur pour mon bridge Philips Hue.

Il semblerait que le message ait été intégré à la v1.4.9 mais que révèle t-il exactement ?
Merci

**Comment by NebzHB** [comment]
Bonjour, il révèle que votre Jeedom n'a pas accès en mDNS (multicast DNS) à vos concentrateur. Il s'agit d'un problème réseau (Par exemple du routage entre jeedom et tes concentrateurs ou un périphérique qui ne propage pas le multicast). Tu dois vérifier dans chaque périphérique réseau se trouvant entre les deux (point d'accès, switch gérable, routeur etc) si tu trouves des paramètres tels que : igmp snooping, multicast, multicast Dns ou mDNS et les activer s'ils sont désactivés mais peut être les désactiver s'ils sont activés car certains switch ou routeurs low cost ont une mauvaise implémentation. On en parle dans la doc du plug-in dans troubleshooting.

Par contre tu as de la chance que j'ai vu ton message car ce n'est pas l'endroit officiel pour poster un problème ! Passe via le support intégré de ta jeedom ou via communauté.

Bien à toi.
